patch_len: 16
stride: 8
d_ff: 128
top_k: 5
d_llm: 768
d_model: 32
n_heads: 8
enc_in: 7
dec_in: 7
dropout: 0.1
learning_rate: 0.0001
max_steps: 50
batch_size: 24
windows_batch_size: 24
early_stop_patience_steps: 10
val_check_steps: 10
